[common] Disable TestManifestGenerateComponentHubTag and testlinter
TestManifestGenerateComponentHubTag does not seem to like the fact we
have an include in our cni daemonset manifest...

{Failed  Running test command using istioctl manifest generate

Error: template: cni/templates/daemonset.yaml:23:32: executing "cni/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap-cni.yaml") .>: error calling include: template: no template "cni/templates/configmap-cni.yaml" associated with template "gotpl"
    manifest-generate_test.go:198: error template: cni/templates/daemonset.yaml:23:32: executing "cni/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap-cni.yaml") .>: error calling include: template: no template "cni/templates/configmap-cni.yaml" associated with template "gotpl": }

So for now, disable the test and disable testlinter since it does not
allow us to skip tests without an issue in upstream.

Signed-off-by: Daniel Hawton <daniel.hawton@solo.io>